package ufsc.bd1.org.model;

// default package
// Generated Jun 18, 2016 6:51:54 PM by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Exemplar generated by hbm2java
 */
public class Exemplar implements java.io.Serializable {

	private int idExemplar;
	private Item item;
	private String corredor;
	private String box;
	private String prateleira;
	private Set utilizas = new HashSet(0);

	public Exemplar() {
	}

	public Exemplar(int idExemplar) {
		this.idExemplar = idExemplar;
	}

	public Exemplar(int idExemplar, Item item, String corredor, String box, String prateleira, Set utilizas) {
		this.idExemplar = idExemplar;
		this.item = item;
		this.corredor = corredor;
		this.box = box;
		this.prateleira = prateleira;
		this.utilizas = utilizas;
	}

	public int getIdExemplar() {
		return this.idExemplar;
	}

	public void setIdExemplar(int idExemplar) {
		this.idExemplar = idExemplar;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public String getCorredor() {
		return this.corredor;
	}

	public void setCorredor(String corredor) {
		this.corredor = corredor;
	}

	public String getBox() {
		return this.box;
	}

	public void setBox(String box) {
		this.box = box;
	}

	public String getPrateleira() {
		return this.prateleira;
	}

	public void setPrateleira(String prateleira) {
		this.prateleira = prateleira;
	}

	public Set getUtilizas() {
		return this.utilizas;
	}

	public void setUtilizas(Set utilizas) {
		this.utilizas = utilizas;
	}

}
