// default package
// Generated Jun 18, 2016 6:51:54 PM by Hibernate Tools 4.0.0.Final
package ufsc.bd1.org.model;

/**
 * FornecedorComponente generated by hbm2java
 */
public class FornecedorComponente implements java.io.Serializable {

	private int idSequencia;
	private Item item;
	private Fornecedor fornecedor;

	public FornecedorComponente() {
	}

	public FornecedorComponente(int idSequencia) {
		this.idSequencia = idSequencia;
	}

	public FornecedorComponente(int idSequencia, Item item, Fornecedor fornecedor) {
		this.idSequencia = idSequencia;
		this.item = item;
		this.fornecedor = fornecedor;
	}

	public int getIdSequencia() {
		return this.idSequencia;
	}

	public void setIdSequencia(int idSequencia) {
		this.idSequencia = idSequencia;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public Fornecedor getFornecedor() {
		return this.fornecedor;
	}

	public void setFornecedor(Fornecedor fornecedor) {
		this.fornecedor = fornecedor;
	}

}
