// default package
// Generated Jun 18, 2016 6:51:54 PM by Hibernate Tools 4.0.0.Final
package ufsc.bd1.org.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Id;


/**
 * Fornecedor generated by hbm2java
 */

@Entity
@Table(name = "fornecedor")
public class Fornecedor implements java.io.Serializable {

	@Id
	private int idFornecedor;
	private String nome;
	private String endereco;
	private String website;
	private int idfornecedor;
	private Set<?> fornecedorComponentes = new HashSet<Object>(0);
	private Set<?> pedidos = new HashSet<Object>(0);

	public Fornecedor() {
	}

	public Fornecedor(int idFornecedor, int idfornecedor) {
		this.idFornecedor = idFornecedor;
		this.idfornecedor = idfornecedor;
	}
	
	public Fornecedor(int idFornecedor, String nome, String endereco, String website) {
		this.idFornecedor = idFornecedor;
		this.nome = nome;
		this.endereco = endereco;
		this.website = website;
	}

	public Fornecedor(int idFornecedor, String nome, String endereco, String website, int idfornecedor,
			Set<?> fornecedorComponentes, Set<?> pedidos) {
		this.idFornecedor = idFornecedor;
		this.nome = nome;
		this.endereco = endereco;
		this.website = website;
		this.idfornecedor = idfornecedor;
		this.fornecedorComponentes = fornecedorComponentes;
		this.pedidos = pedidos;
	}

	public int getIdFornecedor() {
		return this.idFornecedor;
	}

	public void setIdFornecedor(int idFornecedor) {
		this.idFornecedor = idFornecedor;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public int getIdfornecedor() {
		return this.idfornecedor;
	}

	public void setIdfornecedor(int idfornecedor) {
		this.idfornecedor = idfornecedor;
	}

	public Set<?> getFornecedorComponentes() {
		return this.fornecedorComponentes;
	}

	public void setFornecedorComponentes(Set<?> fornecedorComponentes) {
		this.fornecedorComponentes = fornecedorComponentes;
	}

	public Set<?> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<?> pedidos) {
		this.pedidos = pedidos;
	}

}
