// default package
// Generated Jun 18, 2016 6:51:54 PM by Hibernate Tools 4.0.0.Final
package ufsc.bd1.org.model;

/**
 * Funcao generated by hbm2java
 */
public class Funcao implements java.io.Serializable {

	private FuncaoId id;
	private Pessoa pessoa;
	private String funcao;

	public Funcao() {
	}

	public Funcao(FuncaoId id, Pessoa pessoa) {
		this.id = id;
		this.pessoa = pessoa;
	}

	public Funcao(FuncaoId id, Pessoa pessoa, String funcao) {
		this.id = id;
		this.pessoa = pessoa;
		this.funcao = funcao;
	}

	public FuncaoId getId() {
		return this.id;
	}

	public void setId(FuncaoId id) {
		this.id = id;
	}

	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	public String getFuncao() {
		return this.funcao;
	}

	public void setFuncao(String funcao) {
		this.funcao = funcao;
	}

}
