// default package
// Generated Jun 18, 2016 6:51:54 PM by Hibernate Tools 4.0.0.Final
package ufsc.bd1.org.model;

/**
 * FuncaoId generated by hbm2java
 */
public class FuncaoId implements java.io.Serializable {

	private int idFuncao;
	private int idPessoa;

	public FuncaoId() {
	}

	public FuncaoId(int idFuncao, int idPessoa) {
		this.idFuncao = idFuncao;
		this.idPessoa = idPessoa;
	}

	public int getIdFuncao() {
		return this.idFuncao;
	}

	public void setIdFuncao(int idFuncao) {
		this.idFuncao = idFuncao;
	}

	public int getIdPessoa() {
		return this.idPessoa;
	}

	public void setIdPessoa(int idPessoa) {
		this.idPessoa = idPessoa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FuncaoId))
			return false;
		FuncaoId castOther = (FuncaoId) other;

		return (this.getIdFuncao() == castOther.getIdFuncao()) && (this.getIdPessoa() == castOther.getIdPessoa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdFuncao();
		result = 37 * result + this.getIdPessoa();
		return result;
	}

}
