// default package
// Generated Jun 18, 2016 6:51:54 PM by Hibernate Tools 4.0.0.Final
package ufsc.bd1.org.model;

import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable {

	private int idComponente;
	private Float valor;
	private String modelo;
	private String descricao;
	private String tipo;
	private Set fornecedorComponentes = new HashSet(0);
	private Set pedidoComponentes = new HashSet(0);
	private Set exemplars = new HashSet(0);

	public Item() {
	}

	public Item(int idComponente) {
		this.idComponente = idComponente;
	}

	public Item(int idComponente, Float valor, String modelo, String descricao, String tipo, Set fornecedorComponentes,
			Set pedidoComponentes, Set exemplars) {
		this.idComponente = idComponente;
		this.valor = valor;
		this.modelo = modelo;
		this.descricao = descricao;
		this.tipo = tipo;
		this.fornecedorComponentes = fornecedorComponentes;
		this.pedidoComponentes = pedidoComponentes;
		this.exemplars = exemplars;
	}

	public int getIdComponente() {
		return this.idComponente;
	}

	public void setIdComponente(int idComponente) {
		this.idComponente = idComponente;
	}

	public Float getValor() {
		return this.valor;
	}

	public void setValor(Float valor) {
		this.valor = valor;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Set getFornecedorComponentes() {
		return this.fornecedorComponentes;
	}

	public void setFornecedorComponentes(Set fornecedorComponentes) {
		this.fornecedorComponentes = fornecedorComponentes;
	}

	public Set getPedidoComponentes() {
		return this.pedidoComponentes;
	}

	public void setPedidoComponentes(Set pedidoComponentes) {
		this.pedidoComponentes = pedidoComponentes;
	}

	public Set getExemplars() {
		return this.exemplars;
	}

	public void setExemplars(Set exemplars) {
		this.exemplars = exemplars;
	}

}
