// default package
// Generated Jun 18, 2016 6:51:54 PM by Hibernate Tools 4.0.0.Final
package ufsc.bd1.org.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido implements java.io.Serializable {

	private int idPedido;
	private Pessoa pessoa;
	private Fornecedor fornecedor;
	private Date dataPedido;
	private String descricao;
	private Set pedidoComponentes = new HashSet(0);

	public Pedido() {
	}

	public Pedido(int idPedido) {
		this.idPedido = idPedido;
	}

	public Pedido(int idPedido, Pessoa pessoa, Fornecedor fornecedor, Date dataPedido, String descricao,
			Set pedidoComponentes) {
		this.idPedido = idPedido;
		this.pessoa = pessoa;
		this.fornecedor = fornecedor;
		this.dataPedido = dataPedido;
		this.descricao = descricao;
		this.pedidoComponentes = pedidoComponentes;
	}

	public int getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(int idPedido) {
		this.idPedido = idPedido;
	}

	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	public Fornecedor getFornecedor() {
		return this.fornecedor;
	}

	public void setFornecedor(Fornecedor fornecedor) {
		this.fornecedor = fornecedor;
	}

	public Date getDataPedido() {
		return this.dataPedido;
	}

	public void setDataPedido(Date dataPedido) {
		this.dataPedido = dataPedido;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public Set getPedidoComponentes() {
		return this.pedidoComponentes;
	}

	public void setPedidoComponentes(Set pedidoComponentes) {
		this.pedidoComponentes = pedidoComponentes;
	}

}
