// default package
// Generated Jun 18, 2016 6:51:54 PM by Hibernate Tools 4.0.0.Final
package ufsc.bd1.org.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa implements java.io.Serializable {

	private int idPessoa;
	private String universidade;
	private String formacao;
	private String curso;
	private String endereco;
	private String email;
	private Float salario;
	private Date dataAdimissao;
	private String nome;
	private Set utilizas = new HashSet(0);
	private Set solicitas = new HashSet(0);
	private Set pedidos = new HashSet(0);
	private Set pessoaProjetos = new HashSet(0);
	private Set tipoPessoas = new HashSet(0);
	private Set recebes = new HashSet(0);
	private Set funcaos = new HashSet(0);

	public Pessoa() {
	}

	public Pessoa(int idPessoa) {
		this.idPessoa = idPessoa;
	}

	public Pessoa(int idPessoa, String universidade, String formacao, String curso, String endereco, String email,
			Float salario, Date dataAdimissao, String nome, Set utilizas, Set solicitas, Set pedidos,
			Set pessoaProjetos, Set tipoPessoas, Set recebes, Set funcaos) {
		this.idPessoa = idPessoa;
		this.universidade = universidade;
		this.formacao = formacao;
		this.curso = curso;
		this.endereco = endereco;
		this.email = email;
		this.salario = salario;
		this.dataAdimissao = dataAdimissao;
		this.nome = nome;
		this.utilizas = utilizas;
		this.solicitas = solicitas;
		this.pedidos = pedidos;
		this.pessoaProjetos = pessoaProjetos;
		this.tipoPessoas = tipoPessoas;
		this.recebes = recebes;
		this.funcaos = funcaos;
	}

	public int getIdPessoa() {
		return this.idPessoa;
	}

	public void setIdPessoa(int idPessoa) {
		this.idPessoa = idPessoa;
	}

	public String getUniversidade() {
		return this.universidade;
	}

	public void setUniversidade(String universidade) {
		this.universidade = universidade;
	}

	public String getFormacao() {
		return this.formacao;
	}

	public void setFormacao(String formacao) {
		this.formacao = formacao;
	}

	public String getCurso() {
		return this.curso;
	}

	public void setCurso(String curso) {
		this.curso = curso;
	}

	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Float getSalario() {
		return this.salario;
	}

	public void setSalario(Float salario) {
		this.salario = salario;
	}

	public Date getDataAdimissao() {
		return this.dataAdimissao;
	}

	public void setDataAdimissao(Date dataAdimissao) {
		this.dataAdimissao = dataAdimissao;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set getUtilizas() {
		return this.utilizas;
	}

	public void setUtilizas(Set utilizas) {
		this.utilizas = utilizas;
	}

	public Set getSolicitas() {
		return this.solicitas;
	}

	public void setSolicitas(Set solicitas) {
		this.solicitas = solicitas;
	}

	public Set getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set pedidos) {
		this.pedidos = pedidos;
	}

	public Set getPessoaProjetos() {
		return this.pessoaProjetos;
	}

	public void setPessoaProjetos(Set pessoaProjetos) {
		this.pessoaProjetos = pessoaProjetos;
	}

	public Set getTipoPessoas() {
		return this.tipoPessoas;
	}

	public void setTipoPessoas(Set tipoPessoas) {
		this.tipoPessoas = tipoPessoas;
	}

	public Set getRecebes() {
		return this.recebes;
	}

	public void setRecebes(Set recebes) {
		this.recebes = recebes;
	}

	public Set getFuncaos() {
		return this.funcaos;
	}

	public void setFuncaos(Set funcaos) {
		this.funcaos = funcaos;
	}

}
