// default package
// Generated Jun 18, 2016 6:51:54 PM by Hibernate Tools 4.0.0.Final
package ufsc.bd1.org.model;

/**
 * Recebe generated by hbm2java
 */
public class Recebe implements java.io.Serializable {

	private int idSequencia;
	private Pessoa pessoa;
	private Solicitacao solicitacao;

	public Recebe() {
	}

	public Recebe(int idSequencia) {
		this.idSequencia = idSequencia;
	}

	public Recebe(int idSequencia, Pessoa pessoa, Solicitacao solicitacao) {
		this.idSequencia = idSequencia;
		this.pessoa = pessoa;
		this.solicitacao = solicitacao;
	}

	public int getIdSequencia() {
		return this.idSequencia;
	}

	public void setIdSequencia(int idSequencia) {
		this.idSequencia = idSequencia;
	}

	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	public Solicitacao getSolicitacao() {
		return this.solicitacao;
	}

	public void setSolicitacao(Solicitacao solicitacao) {
		this.solicitacao = solicitacao;
	}

}
