// default package
// Generated Jun 18, 2016 6:51:54 PM by Hibernate Tools 4.0.0.Final
package ufsc.bd1.org.model;

import java.util.Date;

/**
 * Solicita generated by hbm2java
 */
public class Solicita implements java.io.Serializable {

	private SolicitaId id;
	private Pessoa pessoa;
	private Projeto projeto;
	private Solicitacao solicitacao;
	private Date data;

	public Solicita() {
	}

	public Solicita(SolicitaId id, Solicitacao solicitacao) {
		this.id = id;
		this.solicitacao = solicitacao;
	}

	public Solicita(SolicitaId id, Pessoa pessoa, Projeto projeto, Solicitacao solicitacao, Date data) {
		this.id = id;
		this.pessoa = pessoa;
		this.projeto = projeto;
		this.solicitacao = solicitacao;
		this.data = data;
	}

	public SolicitaId getId() {
		return this.id;
	}

	public void setId(SolicitaId id) {
		this.id = id;
	}

	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	public Projeto getProjeto() {
		return this.projeto;
	}

	public void setProjeto(Projeto projeto) {
		this.projeto = projeto;
	}

	public Solicitacao getSolicitacao() {
		return this.solicitacao;
	}

	public void setSolicitacao(Solicitacao solicitacao) {
		this.solicitacao = solicitacao;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

}
