// default package
// Generated Jun 18, 2016 6:51:54 PM by Hibernate Tools 4.0.0.Final
package ufsc.bd1.org.model;

import java.util.HashSet;
import java.util.Set;

/**
 * Solicitacao generated by hbm2java
 */
public class Solicitacao implements java.io.Serializable {

	private int idSolicitacao;
	private String item;
	private String descricao;
	private Set solicitas = new HashSet(0);
	private Set recebes = new HashSet(0);

	public Solicitacao() {
	}

	public Solicitacao(int idSolicitacao) {
		this.idSolicitacao = idSolicitacao;
	}

	public Solicitacao(int idSolicitacao, String item, String descricao, Set solicitas, Set recebes) {
		this.idSolicitacao = idSolicitacao;
		this.item = item;
		this.descricao = descricao;
		this.solicitas = solicitas;
		this.recebes = recebes;
	}

	public int getIdSolicitacao() {
		return this.idSolicitacao;
	}

	public void setIdSolicitacao(int idSolicitacao) {
		this.idSolicitacao = idSolicitacao;
	}

	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public Set getSolicitas() {
		return this.solicitas;
	}

	public void setSolicitas(Set solicitas) {
		this.solicitas = solicitas;
	}

	public Set getRecebes() {
		return this.recebes;
	}

	public void setRecebes(Set recebes) {
		this.recebes = recebes;
	}

}
