// default package
// Generated Jun 18, 2016 6:51:54 PM by Hibernate Tools 4.0.0.Final
package ufsc.bd1.org.model;

/**
 * SolicitaId generated by hbm2java
 */
public class SolicitaId implements java.io.Serializable {

	private int idSequencia;
	private int idSolicitacao;

	public SolicitaId() {
	}

	public SolicitaId(int idSequencia, int idSolicitacao) {
		this.idSequencia = idSequencia;
		this.idSolicitacao = idSolicitacao;
	}

	public int getIdSequencia() {
		return this.idSequencia;
	}

	public void setIdSequencia(int idSequencia) {
		this.idSequencia = idSequencia;
	}

	public int getIdSolicitacao() {
		return this.idSolicitacao;
	}

	public void setIdSolicitacao(int idSolicitacao) {
		this.idSolicitacao = idSolicitacao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SolicitaId))
			return false;
		SolicitaId castOther = (SolicitaId) other;

		return (this.getIdSequencia() == castOther.getIdSequencia())
				&& (this.getIdSolicitacao() == castOther.getIdSolicitacao());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdSequencia();
		result = 37 * result + this.getIdSolicitacao();
		return result;
	}

}
