// default package
// Generated Jun 18, 2016 6:51:54 PM by Hibernate Tools 4.0.0.Final
package ufsc.bd1.org.model;

/**
 * TipoPessoa generated by hbm2java
 */
public class TipoPessoa implements java.io.Serializable {

	private TipoPessoaId id;
	private Pessoa pessoa;
	private String tipo;

	public TipoPessoa() {
	}

	public TipoPessoa(TipoPessoaId id, Pessoa pessoa) {
		this.id = id;
		this.pessoa = pessoa;
	}

	public TipoPessoa(TipoPessoaId id, Pessoa pessoa, String tipo) {
		this.id = id;
		this.pessoa = pessoa;
		this.tipo = tipo;
	}

	public TipoPessoaId getId() {
		return this.id;
	}

	public void setId(TipoPessoaId id) {
		this.id = id;
	}

	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
