// default package
// Generated Jun 18, 2016 6:51:54 PM by Hibernate Tools 4.0.0.Final
package ufsc.bd1.org.model;

/**
 * TipoPessoaId generated by hbm2java
 */
public class TipoPessoaId implements java.io.Serializable {

	private int idTipoPessoa;
	private int idPessoa;

	public TipoPessoaId() {
	}

	public TipoPessoaId(int idTipoPessoa, int idPessoa) {
		this.idTipoPessoa = idTipoPessoa;
		this.idPessoa = idPessoa;
	}

	public int getIdTipoPessoa() {
		return this.idTipoPessoa;
	}

	public void setIdTipoPessoa(int idTipoPessoa) {
		this.idTipoPessoa = idTipoPessoa;
	}

	public int getIdPessoa() {
		return this.idPessoa;
	}

	public void setIdPessoa(int idPessoa) {
		this.idPessoa = idPessoa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TipoPessoaId))
			return false;
		TipoPessoaId castOther = (TipoPessoaId) other;

		return (this.getIdTipoPessoa() == castOther.getIdTipoPessoa())
				&& (this.getIdPessoa() == castOther.getIdPessoa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTipoPessoa();
		result = 37 * result + this.getIdPessoa();
		return result;
	}

}
