// default package
// Generated Jun 18, 2016 6:51:54 PM by Hibernate Tools 4.0.0.Final
package ufsc.bd1.org.model;

/**
 * UtilizaId generated by hbm2java
 */
public class UtilizaId implements java.io.Serializable {

	private int idSequencia;
	private int idExemplar;

	public UtilizaId() {
	}

	public UtilizaId(int idSequencia, int idExemplar) {
		this.idSequencia = idSequencia;
		this.idExemplar = idExemplar;
	}

	public int getIdSequencia() {
		return this.idSequencia;
	}

	public void setIdSequencia(int idSequencia) {
		this.idSequencia = idSequencia;
	}

	public int getIdExemplar() {
		return this.idExemplar;
	}

	public void setIdExemplar(int idExemplar) {
		this.idExemplar = idExemplar;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UtilizaId))
			return false;
		UtilizaId castOther = (UtilizaId) other;

		return (this.getIdSequencia() == castOther.getIdSequencia())
				&& (this.getIdExemplar() == castOther.getIdExemplar());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdSequencia();
		result = 37 * result + this.getIdExemplar();
		return result;
	}

}
