// default package
// Generated Jun 18, 2016 6:51:54 PM by Hibernate Tools 4.0.0.Final
package ufsc.bd1.org.model;

import java.util.Date;

/**
 * Utiliza generated by hbm2java
 */
public class Utiliza implements java.io.Serializable {

	private UtilizaId id;
	private Exemplar exemplar;
	private Pessoa pessoa;
	private Projeto projeto;
	private Date dataDevolucao;
	private Date dataEmprestimo;

	public Utiliza() {
	}

	public Utiliza(UtilizaId id, Exemplar exemplar) {
		this.id = id;
		this.exemplar = exemplar;
	}

	public Utiliza(UtilizaId id, Exemplar exemplar, Pessoa pessoa, Projeto projeto, Date dataDevolucao,
			Date dataEmprestimo) {
		this.id = id;
		this.exemplar = exemplar;
		this.pessoa = pessoa;
		this.projeto = projeto;
		this.dataDevolucao = dataDevolucao;
		this.dataEmprestimo = dataEmprestimo;
	}

	public UtilizaId getId() {
		return this.id;
	}

	public void setId(UtilizaId id) {
		this.id = id;
	}

	public Exemplar getExemplar() {
		return this.exemplar;
	}

	public void setExemplar(Exemplar exemplar) {
		this.exemplar = exemplar;
	}

	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	public Projeto getProjeto() {
		return this.projeto;
	}

	public void setProjeto(Projeto projeto) {
		this.projeto = projeto;
	}

	public Date getDataDevolucao() {
		return this.dataDevolucao;
	}

	public void setDataDevolucao(Date dataDevolucao) {
		this.dataDevolucao = dataDevolucao;
	}

	public Date getDataEmprestimo() {
		return this.dataEmprestimo;
	}

	public void setDataEmprestimo(Date dataEmprestimo) {
		this.dataEmprestimo = dataEmprestimo;
	}

}
